modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cossacks_adventure"
version="1.0.0"
displayName="Cossacks Adventure"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="work, MCreator"

[[dependencies.cossacks_adventure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




